### ISSUE TITLE
Count more than 1000

### ISSUE THREAD

**Issue by morning-paradigm** [calumks/anki-more-overview-stats#6]
How can I disable the count limitation? I've tried changing values in 

    # If count is more than 1000, just show 1000+`
    for count in enumerate(counts):
        if len(count) == 1000:
            count = "1000+"

and even deleting the whole block of code, but it didn't help.

Also I can only see `1000`, not `1000+`, no matter what. Other decks with lower counts show right values.

I'm using Anki 2.1 on macOS. I've only discovered this extension after upgrading to 2.1, so I'm not sure if it's related.

**Comment by klieret** [comment]
Yes, the code snippet above code snippet actually does nothing, so removing it also doesn't achieve anything. I am not sure, why the count can't be higher than 1000, but the reason for this seems to lie somewhere (I think you'd have to change the limit in the function ``count_cards``, probably by replacing ``sched.reportLimit`` with some high value). 

Btw, in order to see at least 1000+ as intended above, you can change this too 

    for i, count in enumerate(counts):
        if count > 1000:
	        counts[i] = "1000+"

Cheers,
Kilian
